version: '3.3'
services:

    redis:
      image: "redis:latest"

    auth-db:
      image: "postgres:10"

    movie-db:
      image: "postgres:10"

    eureka:
      ports:
        - "8081:8761"
      build:
        context: ./eureka
      depends_on:
        - redis

    gateway:
      build:
        context: ./gateway
      ports:
        - "80:8080"
      depends_on:
        - eureka
        - redis

    kino_service:
      build:
        context: ./kino-service
      depends_on:
        - gateway
        - redis

    ticket_service:
      build:
        context: ./ticket-service
      depends_on:
        - gateway
        - redis

    user_service:
      build:
        context: ./user-service
      depends_on:
        - gateway
        - redis

    auth_service:
      build:
        context: ./auth-service
      ports:
      - "8082:8080"
      depends_on:
        - gateway
        - redis
        - auth-db

    booking_service:
      build:
        context: ./booking-service
      depends_on:
      - gateway
      - redis

    movie_service:
      build:
        context: ./movie-service
      depends_on:
        - gateway
        - redis
        - movie-db

    frontend:
      build:
        context: ./frontend
      depends_on:
        - gateway